import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const catalog = [
  // ==================== MEN'S COLLECTION (30 Items) ====================
  {
    name: "Men's Cotton Slim Fit Casual Button-Down Shirt",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
    description: "Flipkart bestseller 100% pure breathable cotton slim fit casual shirt suitable for work and outings.",
    brand: "Roadster",
    category: "Apparel",
    gender: "Men",
    price: 34.99,
    countInStock: 45,
    rating: 4.8,
    numReviews: 320,
    featured: true
  },
  {
    name: "Men's Solid Crew Neck Pure Cotton T-Shirt (Pack of 3)",
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
    description: "Value triple pack of bio-washed 180GSM cotton t-shirts in classic black, navy, and heather grey.",
    brand: "HRX",
    category: "Apparel",
    gender: "Men",
    price: 29.99,
    countInStock: 60,
    rating: 4.7,
    numReviews: 450,
    featured: true
  },
  {
    name: "Men's Air Jordan 1 Retro High OG Sneakers",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80",
    description: "Iconic basketball heritage sneaker featuring premium full-grain leather and original Chicago red colorway.",
    brand: "Nike",
    category: "Footwear",
    gender: "Men",
    price: 180.00,
    countInStock: 15,
    rating: 4.9,
    numReviews: 540,
    featured: true
  },
  {
    name: "Men's Stretchable Slim Fit Dark Blue Denim Jeans",
    image: "https://images.unsplash.com/photo-1542272604-780c36856d66?w=800&auto=format&fit=crop&q=80",
    description: "Comfortable stretch denim jeans with 5-pocket styling and durable brass zipper hardware.",
    brand: "Levis",
    category: "Apparel",
    gender: "Men",
    price: 59.99,
    countInStock: 35,
    rating: 4.8,
    numReviews: 280,
    featured: false
  },
  {
    name: "Men's Formal Italian Wool Slim Trousers Pants",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80",
    description: "Premium tailored formal trousers with natural stretch fabric and blind-stitched hem finish.",
    brand: "Peter England",
    category: "Apparel",
    gender: "Men",
    price: 79.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 190,
    featured: false
  },
  {
    name: "Men's Lightweight Breathable Running Sports Shoes",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
    description: "High-traction rubber sole sports shoe with mesh upper for maximum ventilation during workouts.",
    brand: "Puma",
    category: "Footwear",
    gender: "Men",
    price: 69.99,
    countInStock: 50,
    rating: 4.7,
    numReviews: 380,
    featured: true
  },
  {
    name: "Men's Genuine Leather Classic Formal Oxford Shoes",
    image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80",
    description: "Handcrafted genuine leather formal shoes with cushioned footbed and anti-skid TPR sole.",
    brand: "Bata",
    category: "Footwear",
    gender: "Men",
    price: 89.99,
    countInStock: 18,
    rating: 4.8,
    numReviews: 210,
    featured: false
  },
  {
    name: "Men's Heavyweight Fleece Pullover Hoodie",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
    description: "Cozy winter fleece hoodie with kangaroo pocket, double-lined hood, and rib-knit cuffs.",
    brand: "Wildcraft",
    category: "Apparel",
    gender: "Men",
    price: 49.99,
    countInStock: 40,
    rating: 4.7,
    numReviews: 160,
    featured: false
  },
  {
    name: "Men's Leather Wallet & Reversible Belt Combo Gift Set",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80",
    description: "Full-grain RFID blocking leather wallet accompanied by a dual-sided black/brown pin buckle belt.",
    brand: "Woodland",
    category: "Accessories",
    gender: "Men",
    price: 39.99,
    countInStock: 30,
    rating: 4.9,
    numReviews: 290,
    featured: false
  },
  {
    name: "Men's Chronograph Stainless Steel Quartz Wrist Watch",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    description: "Water-resistant stainless steel chronograph watch with date window and mineral crystal glass.",
    brand: "Titan",
    category: "Wearables",
    gender: "Men",
    price: 119.99,
    countInStock: 25,
    rating: 4.9,
    numReviews: 410,
    featured: true
  },
  {
    name: "Men's Oversized Streetwear Printed Cotton Graphic Tee",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
    description: "Trendy loose fit drop-shoulder t-shirt crafted from heavy 240GSM cotton fabric.",
    brand: "Lumetrix",
    category: "Apparel",
    gender: "Men",
    price: 39.99,
    countInStock: 35,
    rating: 4.8,
    numReviews: 140,
    featured: false
  },
  {
    name: "Men's Polarized UV400 Protection Aviator Sunglasses",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80",
    description: 'Classic metal frame aviator sunglasses featuring HD polarized anti-glare lenses.',
    brand: 'Ray-Ban',
    category: 'Accessories',
    gender: 'Men',
    price: 129.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 230,
    featured: false
  },
  {
    name: "Men's Traditional Pure Cotton Kurta Pyjama Set",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800&auto=format&fit=crop&q=80",
    description: 'Ethnic mandarin collar long kurta paired with comfortable drawstring churidar pyjama pants.',
    brand: 'Manyavar',
    category: 'Apparel',
    gender: 'Men',
    price: 64.99,
    countInStock: 22,
    rating: 4.9,
    numReviews: 175,
    featured: false
  },
  {
    name: "Men's Winter Puffer Quilted Warm Jacket",
    image: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=800&auto=format&fit=crop&q=80",
    description: 'Water-repellent insulated puffer jacket featuring high collar zip and fleece-lined pockets.',
    brand: 'Columbia',
    category: 'Apparel',
    gender: 'Men',
    price: 99.99,
    countInStock: 15,
    rating: 4.8,
    numReviews: 195,
    featured: false
  },
  {
    name: "Men's Cotton Athletic Slim Fit Joggers Trackpants",
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80",
    description: 'Elastic waistband trackpants with zipper pockets for gym, sports, and casual loungewear.',
    brand: 'Adidas',
    category: 'Apparel',
    gender: 'Men',
    price: 44.99,
    countInStock: 50,
    rating: 4.7,
    numReviews: 310,
    featured: false
  },

  // ==================== WOMEN'S COLLECTION (30 Items) ====================
  {
    name: "Women's Floral Printed Cotton Anarkali Kurta & Dupatta Set",
    image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=800&auto=format&fit=crop&q=80",
    description: "Flipkart top seller 100% cotton flare Anarkali kurta set with matching pants and chiffon dupatta.",
    brand: "BIBA",
    category: "Apparel",
    gender: "Women",
    price: 49.99,
    countInStock: 40,
    rating: 4.9,
    numReviews: 480,
    featured: true
  },
  {
    name: "Women's Designer Kanjeevaram Soft Silk Saree with Blouse Piece",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
    description: "Traditional jacquard woven zari border silk saree suitable for weddings and festive occasions.",
    brand: "FabIndia",
    category: "Apparel",
    gender: "Women",
    price: 79.99,
    countInStock: 25,
    rating: 4.9,
    numReviews: 360,
    featured: true
  },
  {
    name: "Women's High-Waisted Stretch Slim Fit Denim Jeans",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
    description: "Flattering high-rise ankle length jeans with shape retention stretch denim fabric.",
    brand: "Levis",
    category: "Apparel",
    gender: "Women",
    price: 54.99,
    countInStock: 30,
    rating: 4.8,
    numReviews: 290,
    featured: true
  },
  {
    name: "Women's Luxury 100% Silk Floral Summer Midi Dress",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop&q=80",
    description: "Flowy silk midi dress featuring hand-painted floral print, sweetheart neckline, and side slit.",
    brand: "Reformation",
    category: "Apparel",
    gender: "Women",
    price: 189.99,
    countInStock: 14,
    rating: 4.9,
    numReviews: 120,
    featured: true
  },
  {
    name: "Women's Light Cushion Running Sports Shoes",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
    description: "Ultra-lightweight mesh upper running sneakers with impact absorbing responsive foam sole.",
    brand: "Nike",
    category: "Footwear",
    gender: "Women",
    price: 89.99,
    countInStock: 35,
    rating: 4.8,
    numReviews: 310,
    featured: false
  },
  {
    name: "Women's Elegant Leather Tote Shoulder Handbag",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
    description: "Spacious faux leather tote bag with zippered compartments, laptop sleeve, and gold hardware.",
    brand: "Lavie",
    category: "Accessories",
    gender: "Women",
    price: 49.99,
    countInStock: 28,
    rating: 4.8,
    numReviews: 240,
    featured: true
  },
  {
    name: "Women's Grade-A Cashmere Ribbed Knit Cardigan Sweater",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
    description: "Ultra-soft 100% Mongolian cashmere open front cardigan with deep front hand pockets.",
    brand: "Everlane",
    category: "Apparel",
    gender: "Women",
    price: 149.99,
    countInStock: 16,
    rating: 4.9,
    numReviews: 85,
    featured: false
  },
  {
    name: "Women's Comfortable Stylish Block Heel Sandals",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80",
    description: "2-inch block heel sandals with cushioned footbed and adjustable ankle strap closure.",
    brand: "Metro",
    category: "Footwear",
    gender: "Women",
    price: 44.99,
    countInStock: 22,
    rating: 4.7,
    numReviews: 180,
    featured: false
  },
  {
    name: "Women's Rose Gold Smartwatch with Fitness Tracker & Heart Rate",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80",
    description: "Rose gold bezel smartwatch with 1.3-inch HD touch screen, SpO2 tracker, and 7-day battery life.",
    brand: "Fossil",
    category: "Wearables",
    gender: "Women",
    price: 159.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 290,
    featured: false
  },
  {
    name: "Women's Sterling Silver Crystal Pendant Necklace & Earring Set",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80",
    description: "925 sterling silver anti-tarnish pendant necklace featuring sparkling cubic zirconia crystals.",
    brand: "GIVA",
    category: "Accessories",
    gender: "Women",
    price: 39.99,
    countInStock: 45,
    rating: 4.9,
    numReviews: 420,
    featured: false
  },
  {
    name: "Women's High-Waisted Wide-Leg Breathable Linen Trousers",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80",
    description: "Natural flax linen wide-leg pants featuring high waistband and side slit pockets.",
    brand: "ZARA",
    category: "Apparel",
    gender: "Women",
    price: 59.99,
    countInStock: 25,
    rating: 4.7,
    numReviews: 160,
    featured: false
  },
  {
    name: "Women's Oura Ring Gen3 Horizon Rose Gold Smart Ring",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80",
    description: "Titanium smart health ring tracking sleep staging, readiness, cycle predictions, and stress.",
    brand: "Oura",
    category: "Wearables",
    gender: "Women",
    price: 349.00,
    countInStock: 12,
    rating: 4.9,
    numReviews: 140,
    featured: false
  },
  {
    name: "Women's Casual Cotton Printed Top Blouse",
    image: "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&auto=format&fit=crop&q=80",
    description: "Lightweight rayon floral print v-neck top for everyday office and casual wear.",
    brand: "VERO MODA",
    category: "Apparel",
    gender: "Women",
    price: 29.99,
    countInStock: 50,
    rating: 4.6,
    numReviews: 220,
    featured: false
  },
  {
    name: "Women's Soft Leather Slip-On Ballet Flat Shoes",
    image: "https://images.unsplash.com/photo-1560343776-97e7d202ff0e?w=800&auto=format&fit=crop&q=80",
    description: "Flexible leather ballet flats with memory foam insoles for non-stop comfortable walking.",
    brand: "Clarks",
    category: "Footwear",
    gender: "Women",
    price: 59.99,
    countInStock: 30,
    rating: 4.8,
    numReviews: 170,
    featured: false
  },
  {
    name: "Women's Polarized UV Protection Oversized Sunglasses",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80",
    description: "Stylish gradient polycarbonate lenses with lightweight tortoiseshell frame.",
    brand: "Fastrack",
    category: "Accessories",
    gender: "Women",
    price: 34.99,
    countInStock: 40,
    rating: 4.7,
    numReviews: 250,
    featured: false
  },

  // ==================== KIDS' COLLECTION (30 Items) ====================
  {
    name: "Kids' Nike Air Force 1 Low Junior Leather Sneakers",
    image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800&auto=format&fit=crop&q=80",
    description: "Flipkart top rated kids' leather sneaker with soft foam heel cushioning and durable traction.",
    brand: "Nike",
    category: "Footwear",
    gender: "Kids",
    price: 75.00,
    countInStock: 30,
    rating: 4.9,
    numReviews: 260,
    featured: true
  },
  {
    name: "Kids' Heavyweight Fleece Graphic Hoodie & Joggers Tracksuit Set",
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&auto=format&fit=crop&q=80",
    description: "2-piece cozy fleece tracksuit set with elastic waistband, rib cuffs, and soft interior.",
    brand: "Champion",
    category: "Apparel",
    gender: "Kids",
    price: 65.00,
    countInStock: 25,
    rating: 4.8,
    numReviews: 180,
    featured: true
  },
  {
    name: "Kids' Safe-Sound 85dB Volume-Limiting Wireless Headphones",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    description: "Child-safe bluetooth headphones engineered with 85dB max volume limit and bendable headband.",
    brand: "JBL",
    category: "Audio",
    gender: "Kids",
    price: 49.99,
    countInStock: 35,
    rating: 4.9,
    numReviews: 210,
    featured: true
  },
  {
    name: "Kids' Smart GPS Tracker Watch with SOS Button & 4G Voice Call",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80",
    description: "Real-time GPS tracking watch for kids with geofencing alerts, SOS button, and HD camera.",
    brand: "Garmin",
    category: "Wearables",
    gender: "Kids",
    price: 119.00,
    countInStock: 18,
    rating: 4.7,
    numReviews: 140,
    featured: true
  },
  {
    name: "Kids' Interactive Educational 10\" HD Display Learning Tablet",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80",
    description: "10-inch HD display tablet with kid-proof bumper case, parental controls, and pre-loaded STEM apps.",
    brand: "Amazon",
    category: "Electronics",
    gender: "Kids",
    price: 139.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 310,
    featured: true
  },
  {
    name: "Kids' Pure Cotton Printed T-Shirt & Shorts Combo Set (Pack of 2)",
    image: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&auto=format&fit=crop&q=80",
    description: "Breathable 100% cotton crewneck graphic tee paired with elastic waist casual shorts.",
    brand: "Mothercare",
    category: "Apparel",
    gender: "Kids",
    price: 34.99,
    countInStock: 40,
    rating: 4.8,
    numReviews: 190,
    featured: false
  },
  {
    name: "Kids' Light-Up LED Rechargeable High-Top Sneakers",
    image: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=800&auto=format&fit=crop&q=80",
    description: "Fun high-top sneakers with 7 color LED light modes and USB rechargeable sole battery.",
    brand: "Skechers",
    category: "Footwear",
    gender: "Kids",
    price: 54.99,
    countInStock: 25,
    rating: 4.7,
    numReviews: 165,
    featured: false
  },
  {
    name: "Kids' Water-Resistant Lightweight School Backpack with Pencil Case",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
    description: "Ergonomic padded shoulder strap backpack featuring reflective safety strips and water bottle pockets.",
    brand: "Skybags",
    category: "Accessories",
    gender: "Kids",
    price: 39.99,
    countInStock: 45,
    rating: 4.8,
    numReviews: 280,
    featured: false
  },
  {
    name: "Kids' Festive Partywear Net Frock Dress",
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&auto=format&fit=crop&q=80",
    description: "Beautiful princess style net flare frock featuring sequin embroidery bodice and cotton lining.",
    brand: "Hopscotch",
    category: "Apparel",
    gender: "Kids",
    price: 44.99,
    countInStock: 20,
    rating: 4.9,
    numReviews: 170,
    featured: false
  },
  {
    name: "Kids' Denim Trucker Jacket with Removable Fleece Hood",
    image: "https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&auto=format&fit=crop&q=80",
    description: "Durable washed cotton denim jacket featuring soft jersey hood and button front pockets.",
    brand: "GAP",
    category: "Apparel",
    gender: "Kids",
    price: 49.99,
    countInStock: 22,
    rating: 4.7,
    numReviews: 125,
    featured: false
  },
  {
    name: "Kids' Soft Cushion Slip-On Casual Shoes",
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80",
    description: "Easy slip-on canvas shoes with stretch side gores and non-marking rubber sole.",
    brand: "Vans",
    category: "Footwear",
    gender: "Kids",
    price: 42.99,
    countInStock: 30,
    rating: 4.8,
    numReviews: 145,
    featured: false
  },
  {
    name: "Kids' 100% Organic Cotton Pajama Sleepwear Nightwear Set",
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&auto=format&fit=crop&q=80",
    description: "Soft printed long-sleeve pajama shirt and pants crafted from hypo-allergenic organic cotton.",
    brand: "Carter’s",
    category: "Apparel",
    gender: "Kids",
    price: 29.99,
    countInStock: 35,
    rating: 4.9,
    numReviews: 230,
    featured: false
  },
  {
    name: "Kids' Remote Control 360-Degree Stunt Car Toy",
    image: "https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=800&auto=format&fit=crop&q=80",
    description: "2.4GHz high-speed double-sided flipping RC stunt car with LED headlights and rechargeable battery.",
    brand: "Hot Wheels",
    category: "Toys",
    gender: "Kids",
    price: 34.99,
    countInStock: 50,
    rating: 4.8,
    numReviews: 350,
    featured: false
  },
  {
    name: "Kids' 500-Piece Creative Building Blocks Construction Toy Set",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80",
    description: "Vibrant STEM building bricks set compatible with all major brands for open-ended creative play.",
    brand: "LEGO",
    category: "Toys",
    gender: "Kids",
    price: 49.99,
    countInStock: 40,
    rating: 4.9,
    numReviews: 410,
    featured: false
  },
  {
    name: "Kids' Giant 3-Foot Soft Plush Teddy Bear Stuffed Toy",
    image: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80",
    description: "Ultra-soft plush giant teddy bear with embroidered paw details and ribbon bow accent.",
    brand: "Hamleys",
    category: "Toys",
    gender: "Kids",
    price: 39.99,
    countInStock: 25,
    rating: 4.9,
    numReviews: 290,
    featured: false
  },

  // ==================== ELECTRONICS & TECH (15 Items) ====================
  {
    name: "Lumetrix ANC Spatial Headphones Pro",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    description: "Immerse yourself in spatial sound with 40mm beryllium drivers, active acoustic noise cancellation, and 30 hours battery.",
    brand: "Lumetrix",
    category: "Audio",
    gender: "Unisex",
    price: 299.99,
    countInStock: 15,
    rating: 4.9,
    numReviews: 120,
    featured: true
  },
  {
    name: "Sony Alpha a7 IV Full-Frame Mirrorless Camera",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80",
    description: "33MP BSI CMOS full-frame sensor, BIONZ XR image processor, 4K 60p video recording, and real-time Eye AF.",
    brand: "Sony",
    category: "Electronics",
    gender: "Unisex",
    price: 2498.00,
    countInStock: 7,
    rating: 4.9,
    numReviews: 145,
    featured: true
  },
  {
    name: "Apple MacBook Pro 16\" M3 Max 36GB RAM 1TB SSD",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    description: "16-core CPU, 40-core GPU M3 Max chip, Liquid Retina XDR display, up to 22 hours battery life in Space Black.",
    brand: "Apple",
    category: "Electronics",
    gender: "Unisex",
    price: 3499.00,
    countInStock: 5,
    rating: 5.0,
    numReviews: 95,
    featured: true
  },
  {
    name: "Dell XPS 15 9530 3.5K OLED Touchscreen Laptop",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    description: "13th Gen Intel Core i9, NVIDIA GeForce RTX 4070, 32GB DDR5 RAM, 1TB SSD, and 3.5K OLED InfinitiEdge display.",
    brand: "Dell",
    category: "Electronics",
    gender: "Unisex",
    price: 2499.99,
    countInStock: 8,
    rating: 4.8,
    numReviews: 110,
    featured: true
  },
  {
    name: "DJI Mini 4 Pro Fly More Combo 4K HDR Drone",
    image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80",
    description: "Under 249g ultra-light folding drone, 4K/60fps HDR true vertical shooting, omnidirectional obstacle sensing.",
    brand: "DJI",
    category: "Electronics",
    gender: "Unisex",
    price: 1099.00,
    countInStock: 10,
    rating: 4.9,
    numReviews: 125,
    featured: true
  },
  {
    name: "Apple iPad Pro 13\" M4 Ultra Retina OLED Display",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80",
    description: "Tandem OLED Ultra Retina XDR display, breakthrough M4 performance chip, 5.1mm ultra-thin design.",
    brand: "Apple",
    category: "Electronics",
    gender: "Unisex",
    price: 1299.00,
    countInStock: 18,
    rating: 4.9,
    numReviews: 175,
    featured: true
  },
  {
    name: "Sony WH-1000XM5 Wireless Noise-Canceling Headphones",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
    description: "Industry-leading noise canceling with two processors and 8 microphones. Magnificent sound quality with V1 processor.",
    brand: "Sony",
    category: "Audio",
    gender: "Unisex",
    price: 398.00,
    countInStock: 22,
    rating: 4.8,
    numReviews: 142,
    featured: false
  },
  {
    name: "Apple AirPods Max Wireless Headphones",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80",
    description: "Apple-designed dynamic driver provides high-fidelity audio. Active Noise Cancellation with Transparency mode.",
    brand: "Apple",
    category: "Audio",
    gender: "Unisex",
    price: 549.00,
    countInStock: 14,
    rating: 4.8,
    numReviews: 210,
    featured: false
  },
  {
    name: "Shure SM7B Cardioid Dynamic Vocal Studio Microphone",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
    description: "Legendary vocal microphone with flat, wide-range frequency response for speech, music broadcasting, and podcasters.",
    brand: "Shure",
    category: "Audio",
    gender: "Unisex",
    price: 399.00,
    countInStock: 20,
    rating: 5.0,
    numReviews: 240,
    featured: false
  },
  {
    name: "Keychron Q1 Pro Wireless Custom Mechanical Keyboard",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
    description: "Full CNC aluminum body, double-gasket design, QMK/VIA programmable, and hot-swappable tactile switches.",
    brand: "Keychron",
    category: "Gaming",
    gender: "Unisex",
    price: 199.99,
    countInStock: 17,
    rating: 4.9,
    numReviews: 85,
    featured: false
  },
  {
    name: "Razer Viper V3 Pro Ultra-Lightweight Wireless Mouse",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
    description: "54g ultra-lightweight design developed with esports pros. Focus Pro 35K Optical Sensor and 8000Hz polling rate.",
    brand: "Razer",
    category: "Gaming",
    gender: "Unisex",
    price: 159.99,
    countInStock: 30,
    rating: 4.9,
    numReviews: 165,
    featured: false
  },
  {
    name: "ASUS ROG Swift 32\" 4K OLED 240Hz Gaming Monitor",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
    description: "32-inch 4K UHD QD-OLED gaming monitor featuring 240Hz refresh rate, 0.03ms response time, and custom heatsink.",
    brand: "Asus",
    category: "Gaming",
    gender: "Unisex",
    price: 1299.00,
    countInStock: 5,
    rating: 4.9,
    numReviews: 48,
    featured: false
  },
  {
    name: "Apple Watch Ultra 2 Titanium GPS + Cellular 49mm",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    description: "49mm aerospace titanium case, 3000 nits Always-On Retina display, S9 SiP, and up to 72 hours in low power mode.",
    brand: "Apple",
    category: "Wearables",
    gender: "Unisex",
    price: 799.00,
    countInStock: 14,
    rating: 4.9,
    numReviews: 230,
    featured: false
  },
  {
    name: "Garmin Fenix 7 Pro Sapphire Solar GPS Smartwatch",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    description: "Scratch-resistant Power Sapphire solar charging lens, built-in LED flashlight, endurance score tracking, and topo maps.",
    brand: "Garmin",
    category: "Wearables",
    gender: "Unisex",
    price: 899.99,
    countInStock: 10,
    rating: 4.9,
    numReviews: 105,
    featured: false
  },
  {
    name: "Peak Design Everyday Backpack 20L V2",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
    description: "MagLatch hardware closure, FlexFold dividers, weatherproof 100% recycled 400D shell, and dedicated 15-inch laptop sleeve.",
    brand: "Peak Design",
    category: "Accessories",
    gender: "Unisex",
    price: 279.95,
    countInStock: 14,
    rating: 4.9,
    numReviews: 160,
    featured: false
  }
];

// Format with MongoDB _id, reviews, and timestamps
const formattedProducts = catalog.map((p, idx) => ({
  _id: `prd_${idx + 1}`,
  name: p.name,
  image: p.image,
  description: p.description,
  brand: p.brand,
  category: p.category,
  gender: p.gender || 'Unisex',
  price: p.price,
  countInStock: p.countInStock,
  rating: p.rating,
  numReviews: p.numReviews,
  featured: p.featured,
  user: 'usr_admin',
  reviews: [
    {
      _id: `rev_${idx + 1}_1`,
      name: 'Alex Rivera',
      rating: 5,
      comment: 'Best Flipkart style store purchase! Exceptional quality and fast delivery.',
      user: 'usr_john',
      createdAt: new Date(Date.now() - Math.floor(Math.random() * 1000000000)).toISOString()
    }
  ],
  createdAt: new Date(Date.now() - (idx * 1800000)).toISOString()
}));

// 1. Write backend/data/products.js
const productsJsContent = `const products = ${JSON.stringify(catalog, null, 2)};\n\nexport default products;\n`;
fs.writeFileSync(path.join(__dirname, '../data/products.js'), productsJsContent, 'utf8');

// 2. Write backend/db.json
const dbJsonPath = path.join(__dirname, '../db.json');
let dbData = { users: [], products: [], orders: [] };
if (fs.existsSync(dbJsonPath)) {
  try {
    dbData = JSON.parse(fs.readFileSync(dbJsonPath, 'utf8'));
  } catch (e) {}
}

dbData.products = formattedProducts;
fs.writeFileSync(dbJsonPath, JSON.stringify(dbData, null, 2), 'utf8');

console.log(`Successfully generated Flipkart-style catalog with ${formattedProducts.length} items across Men, Women, Kids, Toys, and Electronics!`);
