import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawProducts = [
  // AUDIO (22 unique items)
  {
    name: 'Lumetrix ANC Spatial Headphones Pro',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    description: 'Immerse yourself in pure spatial sound with custom 40mm beryllium drivers, active acoustic noise cancellation, and up to 30 hours of continuous high-fidelity playback.',
    brand: 'Lumetrix',
    category: 'Audio',
    price: 299.99,
    countInStock: 15,
    rating: 4.9,
    numReviews: 38,
    featured: true
  },
  {
    name: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    description: 'Industry-leading noise canceling with two processors and 8 microphones. Magnificent sound quality with the new Integrated Processor V1.',
    brand: 'Sony',
    category: 'Audio',
    price: 398.00,
    countInStock: 22,
    rating: 4.8,
    numReviews: 142,
    featured: true
  },
  {
    name: 'Bose QuietComfort Ultra Wireless Headphones',
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80',
    description: 'Breakthrough spatialized audio for more immersive listening. World-class noise cancellation and custom-tuned sound calibration.',
    brand: 'Bose',
    category: 'Audio',
    price: 429.00,
    countInStock: 12,
    rating: 4.7,
    numReviews: 89,
    featured: true
  },
  {
    name: 'Sennheiser HD 660S2 Open-Back Audiophile Headphones',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    description: 'Open-back audiophile headphones delivering extended sub-bass impact, precision acoustic transducer tuning, and plush velvet ear cushions.',
    brand: 'Sennheiser',
    category: 'Audio',
    price: 599.95,
    countInStock: 8,
    rating: 4.9,
    numReviews: 45,
    featured: false
  },
  {
    name: 'Apple AirPods Max Wireless Headphones',
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
    description: 'Apple-designed dynamic driver provides high-fidelity audio. Active Noise Cancellation with Transparency mode and Computational audio.',
    brand: 'Apple',
    category: 'Audio',
    price: 549.00,
    countInStock: 14,
    rating: 4.8,
    numReviews: 210,
    featured: true
  },
  {
    name: 'Bang & Olufsen Beoplay H95 Flagship Headphones',
    image: 'https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=800&auto=format&fit=crop&q=80',
    description: 'Crafted with aluminum, lambskin leather, and titanium drivers. Adaptive active noise cancellation and up to 38 hours of playtime.',
    brand: 'Bang & Olufsen',
    category: 'Audio',
    price: 899.00,
    countInStock: 5,
    rating: 4.9,
    numReviews: 27,
    featured: false
  },
  {
    name: 'Marshall Monitor II ANC Wireless Headphones',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    description: 'Iconic vintage rock heritage design with active noise cancelling, ergonomic collapsible fit, and signature Marshall sound profile.',
    brand: 'Marshall',
    category: 'Audio',
    price: 319.99,
    countInStock: 19,
    rating: 4.6,
    numReviews: 63,
    featured: false
  },
  {
    name: 'Shure AONIC 50 Sound Isolating Headphones',
    image: 'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=800&auto=format&fit=crop&q=80',
    description: 'Engineered from decades of stage experience. Premium studio-quality wireless sound with adjustable noise cancellation.',
    brand: 'Shure',
    category: 'Audio',
    price: 349.00,
    countInStock: 10,
    rating: 4.7,
    numReviews: 31,
    featured: false
  },
  {
    name: 'Audio-Technica ATH-M50xBT2 Wireless Studio Headphones',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    description: 'Critically acclaimed M-Series sound in wireless format with 45mm large-aperture drivers and 50 hours battery life.',
    brand: 'AudioPhonic',
    category: 'Audio',
    price: 199.00,
    countInStock: 25,
    rating: 4.8,
    numReviews: 175,
    featured: false
  },
  {
    name: 'Focal Bathys High-Fidelity ANC Wireless Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    description: 'Made in France with Aluminum-Magnesium dome drivers, USB-DAC mode offering 24-bit/192kHz resolution, and back-lit earcups.',
    brand: 'Focal',
    category: 'Audio',
    price: 799.00,
    countInStock: 4,
    rating: 4.9,
    numReviews: 19,
    featured: false
  },
  {
    name: 'Sony WF-1000XM5 Noise-Canceling True Wireless Earbuds',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    description: 'The best noise cancelling earbuds with Dynamic Driver X for richer vocals and enhanced detail reproduction.',
    brand: 'Sony',
    category: 'Audio',
    price: 299.99,
    countInStock: 30,
    rating: 4.7,
    numReviews: 95,
    featured: true
  },
  {
    name: 'Apple AirPods Pro 2nd Gen with USB-C MagSafe Case',
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80',
    description: 'H2 chip power delivers up to 2x more Active Noise Cancellation, Adaptive Audio, and Personalized Spatial Audio.',
    brand: 'Apple',
    category: 'Audio',
    price: 249.00,
    countInStock: 40,
    rating: 4.9,
    numReviews: 310,
    featured: true
  },
  {
    name: 'Bose QuietComfort Ultra Wireless Earbuds',
    image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80',
    description: 'Breakthrough immersive audio and customized sound tuning through CustomTune technology for personalized fit.',
    brand: 'Bose',
    category: 'Audio',
    price: 299.00,
    countInStock: 18,
    rating: 4.6,
    numReviews: 78,
    featured: false
  },
  {
    name: 'Sennheiser Momentum True Wireless 4 Earbuds',
    image: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=800&auto=format&fit=crop&q=80',
    description: 'Lossless audio support with Qualcomm Snapdragon Sound, Auracast broadcasting, and 30-hour battery life.',
    brand: 'Sennheiser',
    category: 'Audio',
    price: 299.95,
    countInStock: 14,
    rating: 4.8,
    numReviews: 42,
    featured: false
  },
  {
    name: 'Jabra Elite 10 Active Noise Cancelling Earbuds',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    description: 'Dolby Atmos Spatial Audio with head tracking, Advanced ANC, and ComfortFit technology for all-day wear.',
    brand: 'Jabra',
    category: 'Audio',
    price: 249.99,
    countInStock: 16,
    rating: 4.5,
    numReviews: 54,
    featured: false
  },
  {
    name: 'Beats Fit Pro True Wireless ANC Earbuds',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    description: 'Flexible secure-fit wingtips, Apple H1 chip for automatic switching, and dynamic head-tracking spatial audio.',
    brand: 'Beats',
    category: 'Audio',
    price: 199.95,
    countInStock: 25,
    rating: 4.6,
    numReviews: 120,
    featured: false
  },
  {
    name: 'Audioengine A2+ Wireless Powered Desktop Speakers',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    description: 'Hand-crafted wood cabinets with silk tweeters and Kevlar woofers. Supports aptX Bluetooth and USB audio input.',
    brand: 'Audioengine',
    category: 'Audio',
    price: 269.00,
    countInStock: 9,
    rating: 4.8,
    numReviews: 88,
    featured: false
  },
  {
    name: 'KEF LSX II Wireless Hi-Fi Speaker System',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    description: 'Uni-Q driver array technology for pristine room-filling high-resolution sound streaming up to 24-bit/384kHz.',
    brand: 'KEF',
    category: 'Audio',
    price: 1399.00,
    countInStock: 3,
    rating: 4.9,
    numReviews: 24,
    featured: true
  },
  {
    name: 'Sonos Era 300 Spatial Audio Smart Speaker',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    description: 'Acoustic architecture with six optimal drivers positioned to project sound from wall to wall and floor to ceiling.',
    brand: 'Sonos',
    category: 'Audio',
    price: 449.00,
    countInStock: 11,
    rating: 4.7,
    numReviews: 66,
    featured: false
  },
  {
    name: 'JBL Authentics 500 Retro Smart Home Speaker',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    description: '270W 3.1 channel speaker with Quadrex grille, aluminum frame, Dolby Atmos music, and dual voice assistants.',
    brand: 'JBL',
    category: 'Audio',
    price: 699.95,
    countInStock: 7,
    rating: 4.8,
    numReviews: 33,
    featured: false
  },
  {
    name: 'Marshall Stanmore III Bluetooth Speaker',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    description: 'Wider soundstage acoustic engineering with outward-angled tweeters and updated waveguides.',
    brand: 'Marshall',
    category: 'Audio',
    price: 379.99,
    countInStock: 15,
    rating: 4.7,
    numReviews: 92,
    featured: false
  },
  {
    name: 'Shure SM7B Cardioid Dynamic Vocal Studio Microphone',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    description: 'Legendary vocal microphone with flat, wide-range frequency response for speech, music broadcasting, and podcasters.',
    brand: 'Shure',
    category: 'Audio',
    price: 399.00,
    countInStock: 20,
    rating: 5.0,
    numReviews: 240,
    featured: true
  },

  // GAMING (22 unique items)
  {
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    description: 'Full CNC aluminum body, double-gasket design, QMK/VIA programmable, and hot-swappable tactile switches.',
    brand: 'Keychron',
    category: 'Gaming',
    price: 199.99,
    countInStock: 17,
    rating: 4.9,
    numReviews: 85,
    featured: true
  },
  {
    name: 'Logitech G Pro X 2 LIGHTSPEED Wireless Gaming Headset',
    image: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=800&auto=format&fit=crop&q=80',
    description: '50mm Graphene drivers for unprecedented clarity, LIGHTSPEED wireless, Bluetooth, and 50-hour battery life.',
    brand: 'Logitech',
    category: 'Gaming',
    price: 249.00,
    countInStock: 21,
    rating: 4.8,
    numReviews: 110,
    featured: true
  },
  {
    name: 'Razer Viper V3 Pro Ultra-Lightweight Wireless Mouse',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    description: '54g ultra-lightweight design developed with esports pros. Gen-2 Focus Pro 35K Optical Sensor and 8000Hz polling rate.',
    brand: 'Razer',
    category: 'Gaming',
    price: 159.99,
    countInStock: 30,
    rating: 4.9,
    numReviews: 165,
    featured: true
  },
  {
    name: 'SteelSeries Apex Pro TKL Wireless Mechanical Keyboard',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    description: 'OmniPoint 2.0 adjustable hypermagnetic switches for 20x faster actuation and rapid trigger performance.',
    brand: 'SteelSeries',
    category: 'Gaming',
    price: 249.99,
    countInStock: 14,
    rating: 4.8,
    numReviews: 73,
    featured: false
  },
  {
    name: 'Corsair K100 RGB Optical-Mechanical Gaming Keyboard',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    description: 'Corsair OPX optical keyswitches with 4000Hz hyper-polling powered by AXON hyper-processing technology.',
    brand: 'Corsair',
    category: 'Gaming',
    price: 229.99,
    countInStock: 11,
    rating: 4.7,
    numReviews: 94,
    featured: false
  },
  {
    name: 'ASUS ROG Swift 32" 4K OLED 240Hz Gaming Monitor',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    description: '32-inch 4K UHD QD-OLED gaming monitor featuring 240Hz refresh rate, 0.03ms response time, and custom heatsink.',
    brand: 'Asus',
    category: 'Gaming',
    price: 1299.00,
    countInStock: 5,
    rating: 4.9,
    numReviews: 48,
    featured: true
  },
  {
    name: 'Alienware AW3423DWF 34" QD-OLED Curved Monitor',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    description: 'Quantum Dot OLED curve monitor with 165Hz refresh rate, VESA DisplayHDR True Black 400, and AMD FreeSync Premium Pro.',
    brand: 'Alienware',
    category: 'Gaming',
    price: 899.99,
    countInStock: 8,
    rating: 4.9,
    numReviews: 180,
    featured: true
  },
  {
    name: 'Samsung Odyssey OLED G9 49" Ultrawide Gaming Monitor',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    description: 'Dual QHD 49-inch curved screen with Neo Quantum Processor Pro, 240Hz refresh rate, and 0.03ms response time.',
    brand: 'Samsung',
    category: 'Gaming',
    price: 1799.99,
    countInStock: 4,
    rating: 4.8,
    numReviews: 62,
    featured: true
  },
  {
    name: 'Scuf Reflex Pro Wireless Performance PS5 Controller',
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80',
    description: 'Four remappable rear paddles, non-slip performance grip, and instant triggers for competitive FPS dominance.',
    brand: 'Scuf',
    category: 'Gaming',
    price: 219.99,
    countInStock: 16,
    rating: 4.7,
    numReviews: 55,
    featured: false
  },
  {
    name: 'PlayStation DualSense Edge Wireless Controller',
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80',
    description: 'Customizable controls, changeable stick caps, back buttons, and replaceable stick modules.',
    brand: 'Sony',
    category: 'Gaming',
    price: 199.99,
    countInStock: 25,
    rating: 4.8,
    numReviews: 130,
    featured: false
  },
  {
    name: 'Xbox Elite Wireless Controller Series 2',
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80',
    description: 'Adjustable-tension thumbsticks, wrap-around rubberized grip, shorter hair trigger locks, and 40 hours battery.',
    brand: 'Microsoft',
    category: 'Gaming',
    price: 179.99,
    countInStock: 20,
    rating: 4.7,
    numReviews: 210,
    featured: false
  },
  {
    name: 'Secretlab TITAN Evo Ergonomic Leatherette Gaming Chair',
    image: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&auto=format&fit=crop&q=80',
    description: '4-way L-ADAPT Lumbar System, magnetic memory foam head pillow, and NEO Hybrid Leatherette durability.',
    brand: 'Secretlab',
    category: 'Gaming',
    price: 549.00,
    countInStock: 10,
    rating: 4.9,
    numReviews: 185,
    featured: false
  },
  {
    name: 'Herman Miller x Logitech G Embody Ergonomic Gaming Chair',
    image: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800&auto=format&fit=crop&q=80',
    description: 'Enhanced ergonomics with copper-infused cooling foam and PostureFit spinal support science.',
    brand: 'Logitech',
    category: 'Gaming',
    price: 1695.00,
    countInStock: 3,
    rating: 5.0,
    numReviews: 44,
    featured: true
  },
  {
    name: 'Elgato Stream Deck MK.2 Studio Controller',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    description: '15 customizable LCD keys to trigger app actions, launch social posts, adjust audio, and switch scenes.',
    brand: 'Elgato',
    category: 'Gaming',
    price: 149.99,
    countInStock: 22,
    rating: 4.9,
    numReviews: 155,
    featured: false
  },
  {
    name: 'Elgato Wave:3 Premium USB Condenser Microphone',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    description: 'Cardioid condenser capsule with anti-distortion Clipguard technology and Wave Link digital mixing app.',
    brand: 'Elgato',
    category: 'Gaming',
    price: 149.99,
    countInStock: 18,
    rating: 4.8,
    numReviews: 98,
    featured: false
  },
  {
    name: 'ASUS ROG Ally X Handheld 1TB Gaming Console',
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80',
    description: 'AMD Ryzen Z1 Extreme processor, 24GB LPDDR5X RAM, 80Wh battery, and 120Hz Full HD VRR display.',
    brand: 'Asus',
    category: 'Gaming',
    price: 799.99,
    countInStock: 9,
    rating: 4.8,
    numReviews: 72,
    featured: true
  },
  {
    name: 'Steam Deck OLED 1TB Handheld Gaming PC',
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80',
    description: '7.4" 90Hz HDR OLED screen, custom APU, Wi-Fi 6E, anti-glare etched glass, and premium carrying case.',
    brand: 'Valve',
    category: 'Gaming',
    price: 649.00,
    countInStock: 12,
    rating: 4.9,
    numReviews: 320,
    featured: true
  },
  {
    name: 'Turtle Beach Stealth Pro Multiplatform Wireless Headset',
    image: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=800&auto=format&fit=crop&q=80',
    description: '50mm Nanoclear hand-matched drivers, swappable dual-battery system, and active noise cancellation.',
    brand: 'Turtle Beach',
    category: 'Gaming',
    price: 329.99,
    countInStock: 8,
    rating: 4.6,
    numReviews: 41,
    featured: false
  },
  {
    name: 'Logitech G502 X PLUS LIGHTSPEED Wireless RGB Mouse',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    description: 'LIGHTFORCE hybrid optical-mechanical switches, HERO 25K gaming sensor, and 8-LED active RGB lighting.',
    brand: 'Logitech',
    category: 'Gaming',
    price: 159.99,
    countInStock: 28,
    rating: 4.8,
    numReviews: 190,
    featured: false
  },
  {
    name: 'Finalmouse UltralightX Tiger Magnesium Mouse',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    description: '35-gram magnesium alloy chassis, wireless 4000Hz polling rate, and Tournament-grade optical sensor.',
    brand: 'Finalmouse',
    category: 'Gaming',
    price: 189.99,
    countInStock: 5,
    rating: 4.9,
    numReviews: 38,
    featured: false
  },
  {
    name: 'Wooting 60HE+ Analog Hall Effect Magnetic Keyboard',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    description: 'Lekker magnetic switches featuring Rapid Trigger mode, dynamic actuation point from 0.1 to 4.0mm.',
    brand: 'Wooting',
    category: 'Gaming',
    price: 174.99,
    countInStock: 7,
    rating: 5.0,
    numReviews: 115,
    featured: true
  },
  {
    name: 'SteelSeries Arctis Nova Pro Wireless Headset',
    image: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=800&auto=format&fit=crop&q=80',
    description: 'Almighty Audio hi-res drivers with Multi-System Infinity DAC station and Active Noise Cancellation.',
    brand: 'SteelSeries',
    category: 'Gaming',
    price: 349.99,
    countInStock: 15,
    rating: 4.8,
    numReviews: 160,
    featured: false
  },

  // WEARABLES (20 unique items)
  {
    name: 'Apple Watch Ultra 2 Titanium GPS + Cellular 49mm',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: '49mm aerospace titanium case, 3000 nits Always-On Retina display, S9 SiP, and up to 72 hours in low power mode.',
    brand: 'Apple',
    category: 'Wearables',
    price: 799.00,
    countInStock: 14,
    rating: 4.9,
    numReviews: 230,
    featured: true
  },
  {
    name: 'Garmin Fenix 7 Pro Sapphire Solar GPS Smartwatch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Scratch-resistant Power Sapphire solar charging lens, built-in LED flashlight, endurance score tracking, and topo maps.',
    brand: 'Garmin',
    category: 'Wearables',
    price: 899.99,
    countInStock: 10,
    rating: 4.9,
    numReviews: 105,
    featured: true
  },
  {
    name: 'Samsung Galaxy Watch6 Classic 47mm Bluetooth',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    description: 'Iconic rotating bezel, Super AMOLED sapphire display, personalized HR zones, and BIA body composition sensor.',
    brand: 'Samsung',
    category: 'Wearables',
    price: 429.99,
    countInStock: 19,
    rating: 4.7,
    numReviews: 88,
    featured: false
  },
  {
    name: 'Oura Ring Gen3 Horizon Titanium Smart Ring',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80',
    description: 'Sleek 360-degree titanium design with research-grade sensors tracking sleep quality, daytime stress, and readiness.',
    brand: 'Oura',
    category: 'Wearables',
    price: 349.00,
    countInStock: 25,
    rating: 4.8,
    numReviews: 140,
    featured: true
  },
  {
    name: 'Ray-Ban Meta Wayfarer Smart Glasses with AI Camera',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
    description: 'Capture 12MP photos and 1080p video, livestream directly to Instagram, open-ear audio, and Meta AI voice command.',
    brand: 'Meta',
    category: 'Wearables',
    price: 329.00,
    countInStock: 16,
    rating: 4.6,
    numReviews: 75,
    featured: true
  },
  {
    name: 'XREAL Air 2 Pro AR Spatial Display Glasses',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
    description: 'Electrochromic dimming lenses, Sony 0.55" Micro-OLED panel, 330" virtual screen display at 120Hz refresh rate.',
    brand: 'XREAL',
    category: 'Wearables',
    price: 449.00,
    countInStock: 11,
    rating: 4.7,
    numReviews: 48,
    featured: false
  },
  {
    name: 'Garmin Epix Pro Gen 2 Sapphire AMOLED Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Stunning 1.4" AMOLED touchscreen display, multi-band GPS with SatIQ technology, and 31-day battery life in smartwatch mode.',
    brand: 'Garmin',
    category: 'Wearables',
    price: 999.99,
    countInStock: 6,
    rating: 4.9,
    numReviews: 52,
    featured: false
  },
  {
    name: 'WHOOP 4.0 Fitness & Health Tracker Band',
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80',
    description: 'Screenless 24/7 continuous wearable monitoring strain, recovery, sleep, skin temperature, and blood oxygen levels.',
    brand: 'WHOOP',
    category: 'Wearables',
    price: 239.00,
    countInStock: 30,
    rating: 4.5,
    numReviews: 160,
    featured: false
  },
  {
    name: 'Google Pixel Watch 2 Polished Silver Smartwatch',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    description: 'All-new multi-path heart rate sensor, Fitbit tracking integration, cEDA stress management, and safety check features.',
    brand: 'Google',
    category: 'Wearables',
    price: 349.99,
    countInStock: 21,
    rating: 4.6,
    numReviews: 67,
    featured: false
  },
  {
    name: 'COROS VERTIX 2S GPS Adventure Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Extreme battery life with 118 hours of continuous full GPS tracking. Dual-frequency dual-satellite positioning.',
    brand: 'COROS',
    category: 'Wearables',
    price: 699.00,
    countInStock: 7,
    rating: 4.8,
    numReviews: 29,
    featured: false
  },
  {
    name: 'Ultrahuman Ring AIR Ergonomic Health Tracker',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80',
    description: 'Ultra-lightweight 2.4g design with Fighter Jet grade titanium, circadian phase alignment tracking, and movement index.',
    brand: 'Ultrahuman',
    category: 'Wearables',
    price: 349.00,
    countInStock: 15,
    rating: 4.7,
    numReviews: 36,
    featured: false
  },
  {
    name: 'Suunto Vertical Titanium Solar Adventure Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Large-screen expedition watch with solar charging, offline dual-band navigation maps, and 85 hours continuous GPS tracking.',
    brand: 'Suunto',
    category: 'Wearables',
    price: 839.00,
    countInStock: 5,
    rating: 4.8,
    numReviews: 23,
    featured: false
  },
  {
    name: 'Apple Watch Series 9 Aluminum GPS 45mm',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
    description: 'S9 chip magic double-tap gesture control, 2000 nits screen brightness, and Precision Finding for iPhone.',
    brand: 'Apple',
    category: 'Wearables',
    price: 429.00,
    countInStock: 28,
    rating: 4.8,
    numReviews: 195,
    featured: false
  },
  {
    name: 'Fitbit Charge 6 Premium Fitness Tracker Band',
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80',
    description: 'Built-in GPS, 60+ workout modes, YouTube Music controls, Google Maps directions, and 7-day battery.',
    brand: 'Fitbit',
    category: 'Wearables',
    price: 159.95,
    countInStock: 35,
    rating: 4.5,
    numReviews: 110,
    featured: false
  },
  {
    name: 'Amazfit T-Rex Ultra Rugged GPS Outdoor Smartwatch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: '316L stainless steel military-grade construction, 30-meter freediving support, 1000 nits AMOLED display, and offline maps.',
    brand: 'Amazfit',
    category: 'Wearables',
    price: 399.99,
    countInStock: 13,
    rating: 4.7,
    numReviews: 44,
    featured: false
  },
  {
    name: 'Rokid Max AR Smart Glasses for Gaming & Cinema',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
    description: '215" borderless Micro-OLED screen experience, 120Hz refresh rate, HDCP support, and directional speakers.',
    brand: 'Rokid',
    category: 'Wearables',
    price: 499.00,
    countInStock: 8,
    rating: 4.6,
    numReviews: 31,
    featured: false
  },
  {
    name: 'Vuzix Blade 2 Smart Glasses for Enterprise AR',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
    description: 'Waveguide optics projection system, integrated HD camera, head tracking sensors, and Android OS integration.',
    brand: 'Vuzix',
    category: 'Wearables',
    price: 1299.00,
    countInStock: 3,
    rating: 4.5,
    numReviews: 14,
    featured: false
  },
  {
    name: 'Circular Ring Slim AI Powered Health Ring',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80',
    description: 'The thinnest smart ring with haptic vibration alarms, bio-signal analysis, and Kira AI health assistant.',
    brand: 'Circular',
    category: 'Wearables',
    price: 275.00,
    countInStock: 12,
    rating: 4.4,
    numReviews: 22,
    featured: false
  },
  {
    name: 'Polar Vantage V3 Premium GPS Multisport Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Polar Elixir biosensing technology, high-resolution AMOLED touchscreen, dual-frequency GPS, and ECG measurement.',
    brand: 'Polar',
    category: 'Wearables',
    price: 599.95,
    countInStock: 9,
    rating: 4.7,
    numReviews: 26,
    featured: false
  },
  {
    name: 'Garmin Tactix 7 AMOLED Edition Tactical Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    description: 'Specialized tactical features with night vision compatibility, stealth mode, dual-format GPS, and white/green LED flashlight.',
    brand: 'Garmin',
    category: 'Wearables',
    price: 1399.99,
    countInStock: 4,
    rating: 4.9,
    numReviews: 38,
    featured: false
  },

  // ELECTRONICS (20 unique items)
  {
    name: 'Sony Alpha a7 IV Full-Frame Mirrorless Camera',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    description: '33MP BSI CMOS full-frame sensor, BIONZ XR image processor, 4K 60p video recording, and real-time Eye AF.',
    brand: 'Sony',
    category: 'Electronics',
    price: 2498.00,
    countInStock: 7,
    rating: 4.9,
    numReviews: 145,
    featured: true
  },
  {
    name: 'Canon EOS R6 Mark II Mirrorless Camera Body',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    description: '24.2MP full-frame CMOS sensor, DIGIC X processor, 40 fps electronic shutter shooting, and 4K 60p uncropped video.',
    brand: 'Canon',
    category: 'Electronics',
    price: 2299.00,
    countInStock: 9,
    rating: 4.9,
    numReviews: 82,
    featured: true
  },
  {
    name: 'Fujifilm X-T5 Mirrorless Camera with 16-80mm Kit',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    description: '40.2MP X-Trans CMOS 5 HR sensor, 7 stops IBIS image stabilization, 6.2K 30p video, and classic dial operation.',
    brand: 'Fujifilm',
    category: 'Electronics',
    price: 2199.00,
    countInStock: 6,
    rating: 4.9,
    numReviews: 64,
    featured: true
  },
  {
    name: 'Apple MacBook Pro 16" M3 Max 36GB RAM 1TB SSD',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: '16-core CPU, 40-core GPU M3 Max chip, Liquid Retina XDR display, up to 22 hours battery life in Space Black.',
    brand: 'Apple',
    category: 'Electronics',
    price: 3499.00,
    countInStock: 5,
    rating: 5.0,
    numReviews: 95,
    featured: true
  },
  {
    name: 'Dell XPS 15 9530 3.5K OLED Touchscreen Laptop',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: '13th Gen Intel Core i9, NVIDIA GeForce RTX 4070, 32GB DDR5 RAM, 1TB SSD, and 3.5K OLED InfinitiEdge display.',
    brand: 'Dell',
    category: 'Electronics',
    price: 2499.99,
    countInStock: 8,
    rating: 4.8,
    numReviews: 110,
    featured: true
  },
  {
    name: 'ASUS ROG Zephyrus G16 OLED Gaming Laptop',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: 'Intel Core Ultra 9 processor, RTX 4080 GPU, 2.5K 240Hz OLED ROG Nebula display in CNC aluminum unibody.',
    brand: 'Asus',
    category: 'Electronics',
    price: 2699.99,
    countInStock: 6,
    rating: 4.9,
    numReviews: 45,
    featured: false
  },
  {
    name: 'Apple iPad Pro 13" M4 Ultra Retina OLED Display',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    description: 'Tandem OLED Ultra Retina XDR display, breakthrough M4 performance chip, 5.1mm ultra-thin design.',
    brand: 'Apple',
    category: 'Electronics',
    price: 1299.00,
    countInStock: 18,
    rating: 4.9,
    numReviews: 175,
    featured: true
  },
  {
    name: 'Samsung Galaxy Tab S9 Ultra 14.6" AMOLED Tablet',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    description: 'Dynamic AMOLED 2X 120Hz 14.6-inch screen, IP68 water resistance, Snapdragon 8 Gen 2, and bundled S Pen.',
    brand: 'Samsung',
    category: 'Electronics',
    price: 1199.99,
    countInStock: 12,
    rating: 4.8,
    numReviews: 88,
    featured: false
  },
  {
    name: 'Anker Nebula Capsule 3 Laser 1080p Mini Projector',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    description: 'Soda-can sized laser projector with 300 ANSI lumens, Google TV, Dolby Digital 8W speakers, and 2.5 hour battery.',
    brand: 'Anker',
    category: 'Electronics',
    price: 799.99,
    countInStock: 15,
    rating: 4.7,
    numReviews: 62,
    featured: false
  },
  {
    name: 'XGIMI HORIZON Ultra 4K Dolby Vision Laser Projector',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    description: 'Dual Light 2300 ISO Lumens projector, Dolby Vision HDR, Harman Kardon audio system, and Intelligent Screen Adaption.',
    brand: 'XGIMI',
    category: 'Electronics',
    price: 1699.00,
    countInStock: 7,
    rating: 4.9,
    numReviews: 39,
    featured: false
  },
  {
    name: 'DJI Mini 4 Pro Fly More Combo 4K HDR Drone',
    image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
    description: 'Under 249g ultra-light folding drone, 4K/60fps HDR true vertical shooting, omnidirectional obstacle sensing, 20km video transmission.',
    brand: 'DJI',
    category: 'Electronics',
    price: 1099.00,
    countInStock: 10,
    rating: 4.9,
    numReviews: 125,
    featured: true
  },
  {
    name: 'DJI Air 3 Dual-Camera 4K Quadcopter Drone',
    image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
    description: '1/1.3-inch CMOS medium tele & wide-angle dual primary cameras, 46-minute flight time, and omnidirectional sensing.',
    brand: 'DJI',
    category: 'Electronics',
    price: 1549.00,
    countInStock: 8,
    rating: 4.8,
    numReviews: 70,
    featured: false
  },
  {
    name: 'Ricoh GR IIIx Digital Camera with 40mm F2.8 Lens',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    description: 'Compact street photography camera with 24.2MP APS-C sensor, 3-axis Shake Reduction, and fast 40mm focal length lens.',
    brand: 'Ricoh',
    category: 'Electronics',
    price: 1049.95,
    countInStock: 11,
    rating: 4.9,
    numReviews: 83,
    featured: false
  },
  {
    name: 'Leica Q3 Compact Full-Frame Digital Camera',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    description: '60MP BSI CMOS full-frame sensor, Summilux 28mm f/1.7 ASPH prime lens, 8K video capability, and OLED viewfinder.',
    brand: 'Leica',
    category: 'Electronics',
    price: 5995.00,
    countInStock: 2,
    rating: 5.0,
    numReviews: 31,
    featured: true
  },
  {
    name: 'Microsoft Surface Laptop 7 Copilot+ PC 15" OLED',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: 'Snapdragon X Elite processor with 45 TOPS NPU AI engine, PixelSense Flow touchscreen, and 22 hour battery life.',
    brand: 'Microsoft',
    category: 'Electronics',
    price: 1499.99,
    countInStock: 15,
    rating: 4.7,
    numReviews: 53,
    featured: false
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Gen 12 Ultrabook',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: 'Carbon-fiber chassis ultrabook powered by Intel Core Ultra processors, 2.8K OLED display, and classic TrackPoint.',
    brand: 'Lenovo',
    category: 'Electronics',
    price: 1849.00,
    countInStock: 10,
    rating: 4.8,
    numReviews: 76,
    featured: false
  },
  {
    name: 'Razer Blade 16 Dual-Mode Mini-LED Gaming Laptop',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    description: 'Intel i9-14900HX, RTX 4090 GPU, world’s first dual-mode Mini-LED display switching between 4K 120Hz & FHD+ 240Hz.',
    brand: 'Razer',
    category: 'Electronics',
    price: 3799.99,
    countInStock: 3,
    rating: 4.9,
    numReviews: 41,
    featured: true
  },
  {
    name: 'GoPro HERO12 Black Action Camera 5.3K Video',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    description: '5.3K60 and 4K120 video, HyperSmooth 6.0 video stabilization, HDR photo/video, Bluetooth audio support, and waterproof to 33ft.',
    brand: 'GoPro',
    category: 'Electronics',
    price: 399.99,
    countInStock: 25,
    rating: 4.7,
    numReviews: 185,
    featured: false
  },
  {
    name: 'Insta360 X4 8K 360-Degree Action Camera',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    description: '8K 30fps 360-degree capture, 5.7K 60fps video, invisible selfie stick effect, FlowState stabilization, and 2.5" touchscreen.',
    brand: 'Insta360',
    category: 'Electronics',
    price: 499.99,
    countInStock: 16,
    rating: 4.8,
    numReviews: 92,
    featured: false
  },
  {
    name: 'reMarkable 2 Paper Tablet with Marker Plus Pen',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    description: 'The world’s thinnest digital paper tablet. CANVAS display engineered to feel just like writing on paper.',
    brand: 'reMarkable',
    category: 'Electronics',
    price: 449.00,
    countInStock: 19,
    rating: 4.7,
    numReviews: 115,
    featured: false
  },

  // ACCESSORIES (20 unique items)
  {
    name: 'Peak Design Everyday Backpack 20L V2',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    description: 'MagLatch hardware closure, FlexFold dividers, weatherproof 100% recycled 400D shell, and dedicated 15-inch laptop sleeve.',
    brand: 'Peak Design',
    category: 'Accessories',
    price: 279.95,
    countInStock: 14,
    rating: 4.9,
    numReviews: 160,
    featured: true
  },
  {
    name: 'Bellroy Classic Backpack Plus 24L Leather Edition',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    description: 'Environmentally certified leather accents, dual compartment storage, contoured lumbar support padding, and water-resistant fabric.',
    brand: 'Bellroy',
    category: 'Accessories',
    price: 239.00,
    countInStock: 12,
    rating: 4.8,
    numReviews: 75,
    featured: false
  },
  {
    name: 'Nomad Horween Leather Folio Case for iPad Pro',
    image: 'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80',
    description: 'Crafted with rustic Horween leather from USA that develops a rich patina over time. Magnetic smart closure.',
    brand: 'Nomad',
    category: 'Accessories',
    price: 149.95,
    countInStock: 20,
    rating: 4.8,
    numReviews: 43,
    featured: false
  },
  {
    name: 'Grovemade Solid Walnut Desk Pad & Laptop Dock',
    image: 'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80',
    description: 'Hand-sanded solid American walnut desktop dock lined with natural wool felt to prevent scratches.',
    brand: 'Grovemade',
    category: 'Accessories',
    price: 170.00,
    countInStock: 10,
    rating: 4.9,
    numReviews: 89,
    featured: true
  },
  {
    name: 'Anker Prime 20,000mAh 200W Power Bank',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    description: '200W total output power across 2 USB-C and 1 USB-A ports. Smart digital display shows realtime power draw.',
    brand: 'Anker',
    category: 'Accessories',
    price: 129.99,
    countInStock: 30,
    rating: 4.9,
    numReviews: 210,
    featured: true
  },
  {
    name: 'Satechi Thunderbolt 4 Multimedia Dock 16-Port',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    description: '16 ports including dual HDMI 2.1, DisplayPort, 96W host charging, 2.5Gb Ethernet, UHS-II SD reader, and audio jack.',
    brand: 'Satechi',
    category: 'Accessories',
    price: 299.99,
    countInStock: 8,
    rating: 4.7,
    numReviews: 52,
    featured: false
  },
  {
    name: 'CalDigit TS4 Thunderbolt 4 Station 18-Port',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    description: 'The ultimate dock with 98W laptop power delivery, 2.5G Ethernet, 8x USB ports, and support for up to dual 6K displays.',
    brand: 'CalDigit',
    category: 'Accessories',
    price: 399.95,
    countInStock: 6,
    rating: 4.9,
    numReviews: 135,
    featured: true
  },
  {
    name: 'Native Union Drop XL Wireless Charging Pad',
    image: 'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80',
    description: 'Powers up to 3 devices simultaneously with multi-coil Qi alignment, textile fabric finish, and aircraft aluminum base.',
    brand: 'Native Union',
    category: 'Accessories',
    price: 149.99,
    countInStock: 15,
    rating: 4.6,
    numReviews: 37,
    featured: false
  },
  {
    name: 'Moft Z 4-in-1 Sit-Stand Ergonomic Desk Laptop Stand',
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop&q=80',
    description: 'Origami folding laptop stand supporting sit-to-stand transition with 5 ergonomic angle positions.',
    brand: 'Moft',
    category: 'Accessories',
    price: 69.99,
    countInStock: 25,
    rating: 4.6,
    numReviews: 81,
    featured: false
  },
  {
    name: 'Orbitkey Nest Portable Desk Organizer with Charger',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Customizable storage compartments for everyday carry accessories topped with a built-in 10W wireless charging lid.',
    brand: 'Orbitkey',
    category: 'Accessories',
    price: 109.00,
    countInStock: 18,
    rating: 4.7,
    numReviews: 60,
    featured: false
  },
  {
    name: 'WaterField Designs Air Porter Leather Travel Case',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    description: 'Handcrafted in San Francisco with ballistic nylon and full-grain premium leather. Designed to fit under airline seats.',
    brand: 'WaterField',
    category: 'Accessories',
    price: 379.00,
    countInStock: 5,
    rating: 4.9,
    numReviews: 29,
    featured: false
  },
  {
    name: 'Twelve South BookArc Vertical Desktop Laptop Stand',
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&auto=format&fit=crop&q=80',
    description: 'Space-saving aluminum vertical desktop stand that holds MacBook closed while connected to external monitor.',
    brand: 'Twelve South',
    category: 'Accessories',
    price: 59.99,
    countInStock: 22,
    rating: 4.7,
    numReviews: 94,
    featured: false
  },
  {
    name: 'Ugreen Nexode 300W GaN 5-Port Fast Desktop Charger',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    description: 'Powerhouse 300W GaN charger capable of delivering 140W fast charge to single USB-C port for 16" laptops.',
    brand: 'Ugreen',
    category: 'Accessories',
    price: 269.99,
    countInStock: 12,
    rating: 4.8,
    numReviews: 47,
    featured: false
  },
  {
    name: 'Baseus 100W Blade Ultra-Thin Digital Power Bank',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    description: '18mm ultra-thin flat profile 20,000mAh battery pack with 100W bi-directional USB-C fast charging.',
    brand: 'Baseus',
    category: 'Accessories',
    price: 99.99,
    countInStock: 28,
    rating: 4.7,
    numReviews: 112,
    featured: false
  },
  {
    name: 'Pitaka MagEZ Slider 3-in-1 Wireless Charging Station',
    image: 'https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80',
    description: 'Rotating compact 3-in-1 desktop charger with removable magnetic power bank for phone, Watch, and AirPods.',
    brand: 'Pitaka',
    category: 'Accessories',
    price: 129.00,
    countInStock: 15,
    rating: 4.6,
    numReviews: 34,
    featured: false
  },
  {
    name: 'Matador Seg42 Travel Pack Convertible Duffel Backpack',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    description: '42-liter maximum capacity travel pack with 5 segmented zip compartments for organized gear separation.',
    brand: 'Matador',
    category: 'Accessories',
    price: 299.99,
    countInStock: 9,
    rating: 4.9,
    numReviews: 28,
    featured: false
  }
];

// Format with MongoDB _id, reviews, and timestamps
const formattedProducts = rawProducts.map((p, idx) => ({
  _id: `prd_${idx + 1}`,
  name: p.name,
  image: p.image,
  description: p.description,
  brand: p.brand,
  category: p.category,
  price: p.price,
  countInStock: p.countInStock,
  rating: p.rating,
  numReviews: p.numReviews,
  featured: p.featured,
  user: 'usr_admin',
  reviews: [
    {
      _id: `rev_${idx + 1}_1`,
      name: 'Alex Rivera',
      rating: 5,
      comment: 'Outstanding quality and fast delivery! Highly recommended.',
      user: 'usr_john',
      createdAt: new Date(Date.now() - Math.floor(Math.random() * 1000000000)).toISOString()
    }
  ],
  createdAt: new Date(Date.now() - (idx * 1800000)).toISOString()
}));

// 1. Write backend/data/products.js
const productsJsContent = `const products = ${JSON.stringify(rawProducts, null, 2)};\n\nexport default products;\n`;
fs.writeFileSync(path.join(__dirname, '../data/products.js'), productsJsContent, 'utf8');

// 2. Write backend/db.json
const dbJsonPath = path.join(__dirname, '../db.json');
let dbData = { users: [], products: [], orders: [] };
if (fs.existsSync(dbJsonPath)) {
  try {
    dbData = JSON.parse(fs.readFileSync(dbJsonPath, 'utf8'));
  } catch (e) {}
}

dbData.products = formattedProducts;
fs.writeFileSync(dbJsonPath, JSON.stringify(dbData, null, 2), 'utf8');

console.log(`Successfully generated ${formattedProducts.length} 100% unique products!`);
